### ISSUE TITLE
no help on singularity

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#102]
Still not sure why, but when i do something like `singularity run -e hippunfold_v0.6.0.sif ` the usage is returned with no problems, and I can run stuff from there. However, when I try to get the extended help, I get the following error:

```
singularity run -e hippunfold_v0.6.0.sif -h
Traceback (most recent call last):
  File "/opt/conda/bin/hippunfold", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/hippunfold/run.py", line 13, in main
    app = SnakeBidsApp(os.path.abspath(os.path.dirname(__file__)))
  File "/opt/conda/lib/python3.7/site-packages/snakebids/app.py", line 200, in __init__
    self.__parse_args()
  File "/opt/conda/lib/python3.7/site-packages/snakebids/app.py", line 312, in __parse_args
    all_args = self.parser.parse_known_args()
  File "/opt/conda/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/conda/lib/python3.7/argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/conda/lib/python3.7/argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "/opt/conda/lib/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/conda/lib/python3.7/argparse.py", line 1043, in __call__
    parser.print_help()
  File "/opt/conda/lib/python3.7/argparse.py", line 2481, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/conda/lib/python3.7/argparse.py", line 2465, in format_help
    return formatter.format_help()
  File "/opt/conda/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/opt/conda/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/opt/conda/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/opt/conda/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/opt/conda/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/opt/conda/lib/python3.7/argparse.py", line 531, in _format_action
    help_text = self._expand_help(action)
  File "/opt/conda/lib/python3.7/argparse.py", line 620, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character ')' (0x29) at index 150
```

The same is true if I shell into the container and call `hippunfold`.

**Comment by akhanf** [comment]
ah this might be a typo I introduced in the config file -- should be an easy fix if so -- will make a PR
