### ISSUE TITLE
Bidsapp missing hippocampal_autotop folder

### ISSUE THREAD

**Issue by myousif9** [khanlab/hippunfold#20]
Hi @akhanf ,
I tried running the hippunfold container on graham and I got this error below. I used `singularity shell` to get into the container and I navigated to `/opt/conda/lib/python3.7/site-packages/hippunfold/` and found no `hippocampal_autotop` directory under it. My guess is that since `khanlab/hippunfold/hippocampal_autotop` links to another github repository then the container is not building with that directory in it. Let me know what you think, thanks!

```
SINGULARITY_IMAGE: /project/6050199/akhanf/singularity/bids-apps/khanlab_hippunfold_latest.sif
CMD: /scratch/myousif9/DM2_grad_corr_bids3 /scratch/myousif9/DM2_hippunfold participant --participant_label S84 --modality T1w --cores 8
START_TIME: Mon Jan 11 23:33:43 EST 2021
WARNING: While bind mounting '/localscratch:/localscratch': destination is already in the mount point list
Building DAG of jobs...
MissingInputException in line 35 of /opt/conda/lib/python3.7/site-packages/hippunfold/workflow/rules/preproc_t1.smk:
Missing input files for rule affine_aladin:
/opt/conda/lib/python3.7/site-packages/hippunfold/hippocampal_autotop/atlases/CITI/CIT168_T1w_head_700um.nii.gz

Traceback (most recent call last):
  File "/opt/conda/bin/hippunfold", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/hippunfold/run.py", line 9, in main
    app.run_snakemake()
  File "/opt/conda/lib/python3.7/site-packages/snakebids/app.py", line 197, in run_snakemake
    run(snakemake_cmd)
  File "/opt/conda/lib/python3.7/site-packages/snakebids/app.py", line 41, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1
RETURNVAL=1
END_TIME: Mon Jan 11 23:34:23 EST 2021
```

**Comment by akhanf** [comment]
This is the same as #19 and actually a new container should be built as of 1 minute ago, but just checking it out now to see if it fixed the problem..

**Comment by myousif9** [comment]
Ahh okay, sounds good then I'll close this issue.
