### ISSUE TITLE
broken workflow, possibly in dependencies

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#312]
Something seems to have broken, I can no longer run any wet or dry runs. This seems to be true whether in singularity or local build.

The only things I can think of are that a dependency broke, or perhaps this recent commit 71d940a4f2097c52769fd8d5ead4154e7f6ff6a9 messed something up in the git actions to bump the version

```
hippunfold-dev/hippunfold-wetrun$ hippunfold lowresMRI test-lowresMRI participant --modality T1w -np
Traceback (most recent call last):
  File "/export03/data/opt/hippunfold-dev/venv/bin/hippunfold", line 8, in <module>
    sys.exit(main())
  File "/export03/data/opt/hippunfold-dev/hippunfold/hippunfold/run.py", line 20, in main
    app.run_snakemake()
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/snakebids/app.py", line 148, in run_snakemake
    self._app.run()
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/snakebids/bidsapp/run.py", line 204, in run
    self.pm.hook.run(config=self.config)
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/snakebids/plugins/snakemake.py", line 331, in run
    snakemake_main(  # type: ignore
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/snakemake/__init__.py", line 2736, in main
    parser = get_argument_parser()
  File "/export03/data/opt/hippunfold-dev/venv/lib/python3.9/site-packages/snakemake/__init__.py", line 1607, in get_argument_parser
    lp_solvers = pulp.list_solvers(onlyAvailable=True)
AttributeError: module 'pulp' has no attribute 'list_solvers'
```

**Comment by akhanf** [comment]
This is something we've come across in other snakemake/snakebids projects. Can you try adding: `pulp = "<2.8.0"` to the poetry dependencies?

**Comment by jordandekraker** [comment]
ah yes, this seems to fix the issue. Do you know of a way I can push this to the latest dockerhub container without changing the release tag?

Also i seem to be getting a new error now, i'll investigate further and start a new issue if needed for it

**Comment by jordandekraker** [comment]
Not sure if its related or not, but here is the new error i'm getting:
```
[UserWarning] /export03/data/opt/hippunfold-dev/hippunfold/hippunfold/workflow/rules/shape_inject.smk:409         "subj"
  Path generated with unrecognized entities, and a snakebids spec has not been explicitly declared. This could break in future snakebids versions, as the default spec can be changed without warning.
      path = './work/sub-{subject}/warps/sub-{subject}_hemi-{hemi}_space-corobl_desc-greedy_from-template_to-subject_xfm.nii.gz'
      entities = ['from-template', 'to-subject']

  Please declare a spec using:
      from snakebids import set_bids_spec
      set_bids_spec("v0_0_0")
```
there are many of these warnings, seemingly for every rule in the workflow, and then the following error:`
```
KeyError in line 382 of /export03/data/opt/hippunfold-dev/hippunfold/hippunfold/workflow/rules/common.smk:
'T1w'
  File "/export03/data/opt/hippunfold-dev/hippunfold/hippunfold/workflow/Snakefile", line 185, in <module>
  File "/export03/data/opt/hippunfold-dev/hippunfold/hippunfold/workflow/rules/common.smk", line 382, in get_final_output
```

**Comment by akhanf** [comment]
You'll need to pin the snakebids version, could use snakebids='>0.5.1,<1.0.0' in the pyproject dependencies.

You can use the publish docker container github action manually, but it will be best to do a patch release 1.5.1 so the github tag is consistent with the docker hub tag. 

Away from my computer right now otherwise would help out!

**Comment by akhanf** [comment]
In the future you can also use the publish docker container workflow manually from any branch to make sure nothing is broken before releasing.
